# Generated by Django 6.1 on 2026-08-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('industry', 'Industry'), ('institution', 'Institution')], default='student', max_length=20),
        ),
    ]
