# Generated by Django 6.1 on 2026-08-30 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacherstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(limit_choices_to={'role': 'institution'}, on_delete=django.db.models.deletion.CASCADE, related_name='institution_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('institution', 'student')},
            },
        ),
    ]
