# Generated by Django 6.1 on 2026-08-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
