# Generated by Django 6.1 on 2026-08-30 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_skillresult_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('skill_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_results', to='assessments.skillresult')),
            ],
        ),
    ]
